name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:

env:
  CHERE_INVOKING: 1

jobs:
  test:
    name: ${{ matrix.gap-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - master
          - '4.14'
          - '4.13'
          - '4.12'
          - '4.11'
          - '4.10'

    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - name: 'Clone the Example package'
        uses: actions/checkout@v5
        with:
          repository: gap-packages/example
      - name: 'Check out this repository'
        uses: actions/checkout@v5
        with:
          path: this-action/
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v3
      - uses: ./this-action/
